version: "3"
services:
  secretsfly:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - gunicorn
      - app:app
      - --log-level=DEBUG
      - --bind=0.0.0.0:4430
    env_file:
      - .env
    environment:
      WEB_CONCURRENCY: 1
      #GUNICORN_CMD_ARGS: --certfile /app/certs/cert.pem --keyfile /app/certs/key.pem
      ENV: production
      FLASK_APP: ./app.py
    network_mode: host
    volumes:
      - ./db:/app/db
