"""Add service tokens table

Revision ID: 494010461397
Revises: 74ede0b4bd94
Create Date: 2023-01-02 20:51:39.178892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494010461397'
down_revision = '74ede0b4bd94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), index=True, nullable=False),
    sa.Column('rights', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_tokens_project_id_environment_id', 'service_tokens', ['project_id', 'environment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_tokens_project_id_environment_id', table_name='service_tokens')
    op.drop_table('service_tokens')
    # ### end Alembic commands ###
