"""Add ServiceToken model

Revision ID: f64a9ca60b41
Revises: bbef4b28de4b
Create Date: 2022-12-31 10:53:43.677702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64a9ca60b41'
down_revision = 'bbef4b28de4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('rights', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_tokens')
    # ### end Alembic commands ###
