name: test-cli

on: [push]

jobs:
  test-cli:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Boot up the sample api server
        run: |
          python tests/sample_api_secrets_server.py &
          sleep 3
          curl http://localhost:5000/api/secrets/ | grep "secret1name"
      - name: Execute the CLI
        run: |
          ls -la